### ISSUE TITLE
Error while running the container

### ISSUE THREAD

**Issue by iamshreeram** [mewil/elastic-graphql#18]
Seeing below error while running the sturgeon container
```
{[host.docker.internal:9200] _all  true false true true}
2021/10/27 11:11:37 unsupported protocol scheme "host.docker.internal"
```

cc: @mewil

**Comment by mewil** [comment]
Hi @iamshreeram, thank you for creating this issue!

Have you tried adding a URL scheme such as `http://` to the beginning of your Elasticsearch server URL? If Sturgeon and Elasticsearch are running in the same Docker network, you can also use the name of the container in the address: `http://<CONTAINER NAME>:9200`

I see the README does not use URL scheme in the example, so I will correct it. Thanks again for reporting this issue.

**Comment by iamshreeram** [comment]
@mewil , Appreciate your response. Using `http://` is throwing below error - 

```
~ ❯❯❯ docker run -e STURGEON_ELASTICSEARCH_HOSTS=http://host.docker.internal:9200 -p 8080:8080 --rm mewil/sturgeon:latest
{[http://host.docker.internal:9200] _all  true false true true}
2021/10/28 10:13:07 RootQuery fields must be an object with field names as keys or a function which return such an object.
```

**Comment by mewil** [comment]
I expect this is a bug. Would it be possible to share your Elasticsearch index mapping? This would help me reproduce and fix the issue.

**Comment by iamshreeram** [comment]
@mewil , There was a issue with the ES instance. Now, our ES instance is working fine and it has 3 indices. But, Sturgeon isn't starting for some reason. Below is the log trace.

```
~ ❯❯❯ docker run -e STURGEON_ELASTICSEARCH_HOSTS=http://host.docker.internal:9200 -p 8080:8080 --rm mewil/sturgeon:latest                                                 (base) 14:45:29
{[http://host.docker.internal:9200] _all  true false true true}
2021/11/01 09:17:38 built document type for kibana_sample_data_flights in 462.1µs
2021/11/01 09:17:38 built document type for .kibana-event-log-7.14.2-000001 in 387µs
2021/11/01 09:17:38 built document type for .tasks in 1.1758ms
2021/11/01 09:17:38 built document type for .kibana_task_manager_7.14.2_001 in 1.2138ms
2021/11/01 09:17:38 built boolean argument type for .tasks in 183.2µs
2021/11/01 09:17:38 built document type for .async-search in 775.6µs
2021/11/01 09:17:38 built boolean argument type for .async-search in 149µs
2021/11/01 09:17:38 built document type for .apm-agent-configuration in 923.9µs
2021/11/01 09:17:38 built document aggregation type for .async-search in 125.5µs
2021/11/01 09:17:38 built document type for kibana_sample_data_ecommerce in 2.0459ms
2021/11/01 09:17:38 built boolean argument type for kibana_sample_data_flights in 1.2437ms
2021/11/01 09:17:38 built boolean argument type for .kibana-event-log-7.14.2-000001 in 1.0527ms
2021/11/01 09:17:38 built boolean argument type for .kibana_task_manager_7.14.2_001 in 264.3µs
2021/11/01 09:17:38 built document type for .apm-custom-link in 778.5µs
2021/11/01 09:17:38 built boolean argument type for .apm-custom-link in 219.7µs
2021/11/01 09:17:38 built document aggregation type for .tasks in 747.6µs
2021/11/01 09:17:38 built document aggregation type for kibana_sample_data_flights in 729.7µs
2021/11/01 09:17:38 built document type for .kibana_7.14.2_001 in 1.0583ms
2021/11/01 09:17:38 built document aggregation type for .kibana_task_manager_7.14.2_001 in 931.4µs
2021/11/01 09:17:38 built document type for kibana_sample_data_logs in 4.3889ms
2021/11/01 09:17:38 built document aggregation type for .apm-custom-link in 794µs
2021/11/01 09:17:38 built document aggregation type for .kibana-event-log-7.14.2-000001 in 1.366ms
2021/11/01 09:17:38 built boolean argument type for .apm-agent-configuration in 2.3509ms
2021/11/01 09:17:38 built document aggregation type for .apm-agent-configuration in 37.5µs
2021/11/01 09:17:38 built boolean argument type for kibana_sample_data_ecommerce in 1.9038ms
2021/11/01 09:17:38 built document aggregation type for kibana_sample_data_ecommerce in 311.7µs
2021/11/01 09:17:38 built boolean argument type for kibana_sample_data_logs in 4.1379ms
2021/11/01 09:17:38 built document aggregation type for kibana_sample_data_logs in 1.2488ms
2021/11/01 09:17:38 built boolean argument type for .kibana_7.14.2_001 in 6.5166ms
2021/11/01 09:17:38 built document aggregation type for .kibana_7.14.2_001 in 3.3575ms
2021/11/01 09:17:38 Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but ".kibana_task_manager_7.14.2_001" does not.
```

**Comment by mewil** [comment]
Which ES index are you looking to generate a schema for? If it is only those starting with `kibana_sample_`, consider setting the environment variable `STURGEON_ELASTICSEARCH_INDEX_INCLUDE_PATTERN=kibana_sample_*`.

This would skip generating schema for indices such as `.kibana_task_manager_7.14.2_001`, whose name is not supported by GraphQL. If you do need that index, I can add logic to creating a GraphQL schema with an appropriate name such as `kibana_task_manager_7_14_2_001`.

**Comment by iamshreeram** [comment]
1. Yes, I'm looking to create schema only for `kibana_sample_` for now. And What If I want to create schema for multiple es indices? should i provide comma separated (`,`) index names? Can this be automated inside Sturgeon?
2. What if I want schema to be created for all the ES index (Except internal ones)? I think we need some way to ignore these internal indices (starts with `.`) 

It would be great, if Sturgeon can just start or understand all these edge cases without any manual inputs. I mean, if sturgeon container just start without breaking, it would be good. Any thoughts?

Can you [enable discussion](https://docs.github.com/en/discussions/quickstart) for this repository?

**Comment by iamshreeram** [comment]
Error while passing `STURGEON_ELASTICSEARCH_INDEX_INCLUDE_PATTERN="kibana_sample_*"`
```
{[http://host.docker.internal:9200] kibana_sample_*  true false true true}
2021/11/02 07:10:59 built document type for kibana_sample_data_flights in 102.207µs
2021/11/02 07:10:59 built document type for kibana_sample_data_logs in 194.352µs
2021/11/02 07:10:59 built document type for kibana_sample_data_ecommerce in 372.207µs
2021/11/02 07:10:59 built boolean argument type for kibana_sample_data_ecommerce in 148.954µs
2021/11/02 07:10:59 built document aggregation type for kibana_sample_data_ecommerce in 92.504µs
2021/11/02 07:10:59 built boolean argument type for kibana_sample_data_logs in 752.318µs
2021/11/02 07:10:59 built boolean argument type for kibana_sample_data_flights in 1.156897ms
2021/11/02 07:10:59 built document aggregation type for kibana_sample_data_logs in 626.046µs
2021/11/02 07:10:59 built document aggregation type for kibana_sample_data_flights in 384.126µs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x560fe5]

goroutine 1 [running]:
github.com/graphql-go/graphql.(*Scalar).Error(0x0, 0xb0ef26, 0x31)
	/go/pkg/mod/github.com/graphql-go/graphql@v0.7.9/definition.go:300 +0x5
github.com/graphql-go/graphql.defineFieldMap(0xbb5c00, 0xc0002ac000, 0xc000282180, 0x0, 0xc00012a000, 0xc00012a000)
	/go/pkg/mod/github.com/graphql-go/graphql@v0.7.9/definition.go:526 +0x29d
github.com/graphql-go/graphql.(*Object).Fields(0xc0002ac000, 0xeab750)
	/go/pkg/mod/github.com/graphql-go/graphql@v0.7.9/definition.go:440 +0x91
github.com/graphql-go/graphql.typeMapReducer(0xc00008da50, 0xc00011a3f0, 0xbbdd60, 0xc0002ac000, 0xc0002ac000, 0x0, 0x0)
	/go/pkg/mod/github.com/graphql-go/graphql@v0.7.9/schema.go:337 +0x4fa
github.com/graphql-go/graphql.typeMapReducer(0xc00008da50, 0xc00011a3f0, 0xbbdd60, 0xc00011e4d0, 0x2, 0xc000064440, 0x1)
	/go/pkg/mod/github.com/graphql-go/graphql@v0.7.9/schema.go:348 +0x6a5
github.com/graphql-go/graphql.NewSchema(0xc00011e4d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/graphql-go/graphql@v0.7.9/schema.go:108 +0x86f
main.buildSchemaFromMappings(0xc000190030, 0xc00021a288, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/mewil/sturgeon/schema.go:37 +0x3dd
main.main()
	/go/src/github.com/mewil/sturgeon/main.go:20 +0x19b
```

**Comment by mewil** [comment]
> 1. Yes, I'm looking to create schema only for kibana_sample_ for now. And What If I want to create schema for multiple es indices? should i provide comma separated (,) index names? Can this be automated inside Sturgeon?

Current only the wildcard approach is supported via `STURGEON_ELASTICSEARCH_INDEX_INCLUDE_PATTERN `, but I can make this a comma-separated list.

> 2. What if I want schema to be created for all the ES index (Except internal ones)? I think we need some way to ignore these internal indices (starts with .)

I think ignoring internal indices by default makes a lot of sense; I can add an exclude index pattern that is `.*` (glob) by default.

> It would be great, if Sturgeon can just start or understand all these edge cases without any manual inputs. I mean, if sturgeon container just start without breaking, it would be good. Any thoughts?

I totally agree, thanks for bearing with me as it gets to that point 😄 

> Can you enable discussion for this repository?

Done

Thanks for sharing that stack trace! I will see if I can root cause the issue.

**Comment by mewil** [comment]
The above `nil` dereference issue should be fixed on the `main` branch now. Can you please try again using the Docker image `mewil/sturgeon:main`?

**Comment by iamshreeram** [comment]
Application is good now. But, when I try accessing graphiql (at http://localhost:8080/graphql), I see below error 

```error.json
{
	"data": null,
	"errors": [
		{
			"message": "Must provide an operation.",
			"locations": []
		}
	]
}
```

Is this expected?

**Comment by mewil** [comment]
I've updated the README to reflect this more clearly, but the flag `STURGEON_ENABLE_GRAPHIQL=true` is necessary to enable the GraphiQL web interface. In your opinion, should it be enabled by default?

cc @iamshreeram

**Comment by iamshreeram** [comment]
@mewil , Yeah, I think so. Most of the graphql dev interact using graphiql. It would be good if we can enable it as default option. Any thoughts?
